import React from 'react'
import { createRoot } from 'react-dom/client'
import App from './App.jsx'
import './index.css'
import './i18n/i18n'
import { registerSW } from 'virtual:pwa-register'

// PWA: register Service Worker (generated by vite-plugin-pwa).
// In dev it's disabled by default (see vite.config.js devOptions).
const updateSW = registerSW({
  immediate: true,
  onNeedRefresh() {
    // Auto-apply updates (refresh will happen after new SW activates)
    updateSW(true)
  },
})

createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
